export const getAllTruck = (payload) => ({ type: 'GET_ALL_TRUCK', payload })
export const getTruck = (payload) => ({ type: 'GET_ATRUCK', payload })
export const addTruck = (payload) => ({ type: 'ADD_TRUCK', payload })
export const updateTruck = (payload) => ({ type: 'UPDATE_TRUCK', payload })
export const deleteTruck = (payload) => ({ type: 'DELETE_TRUCK', payload })
export const searchTruck = (payload) => ({ type: 'SEARCH_TEXT', payload })
